import React, { useMemo, useRef, useState } from 'react';
import JSZip from 'jszip';
import { GoogleGenAI } from '@google/genai';
import { Check, CheckCircle2, Download, FileCode2, FileImage, FileText, Folder, FolderUp, Loader2, Pencil, Play, ShieldCheck, Sparkles } from 'lucide-react';
import { useStore } from '../../store';
import { getGeminiCredential } from '../../lib/credentials';

type Para = 'project' | 'area' | 'resource' | 'archive';
type SourceItem = { id: string; name: string; relativePath: string; type: string; size: number; excerpt: string; modified: string; selected: boolean; kind: 'document' | 'code' | 'image' | 'binary' };
type Proposal = SourceItem & { para: Para; title: string; parent: string; summary: string; tags: string[]; actions: string[]; confidence: number; markdown: string };
const textExtensions = new Set(['md', 'txt', 'csv', 'json', 'yaml', 'yml', 'xml', 'html', 'htm', 'sql', 'js', 'ts', 'tsx', 'jsx', 'py', 'ipynb', 'doc']);
const codeExtensions = new Set(['js', 'ts', 'tsx', 'jsx', 'py', 'ipynb', 'sql', 'html', 'htm']);
const imageExtensions = new Set(['png', 'jpg', 'jpeg', 'gif', 'webp', 'heic', 'svg']);
const ignoredFolders = new Set(['__macosx', '.venv', 'venv', 'node_modules', '__pycache__', '.git']);
const paraLabel: Record<Para, string> = { project: 'Projeto', area: 'Área', resource: 'Recurso', archive: 'Arquivado' };
const intakeKey = 'me_knowledge_intake_v1';
function extension(name: string) { return name.split('.').pop()?.toLowerCase() || 'arquivo'; }
function humanSize(bytes: number) { return bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function cleanJson(value: string) { return value.replace(/^```json\s*/i, '').replace(/```$/i, '').trim(); }
function limit(value: string, max = 2200) { return value.length <= max ? value : `${value.slice(0, max - 1).trimEnd()}…`; }
function isNoise(path: string) { const parts = path.split('/'); const leaf = parts.at(-1) || ''; return parts.some(part => ignoredFolders.has(part.toLowerCase())) || leaf === '.DS_Store' || leaf.startsWith('._'); }
function itemKind(path: string): SourceItem['kind'] { const ext = extension(path); return imageExtensions.has(ext) ? 'image' : codeExtensions.has(ext) ? 'code' : textExtensions.has(ext) || ['pdf', 'docx', 'xlsx'].includes(ext) ? 'document' : 'binary'; }
function baseItem(name: string, size: number, excerpt: string, modified: string): SourceItem { const kind = itemKind(name); return { id: crypto.randomUUID(), name: name.split('/').at(-1) || name, relativePath: name, type: extension(name).toUpperCase(), size, excerpt, modified, selected: kind !== 'image' && kind !== 'binary', kind }; }
function fallback(item: SourceItem): Proposal { const lower = item.name.toLowerCase(); const para: Para = lower.includes('contrato') ? 'archive' : lower.includes('projeto') ? 'project' : 'resource'; return { ...item, para, title: item.name.replace(/\.[^.]+$/, '').replace(/[-_]/g, ' '), parent: '', summary: 'Proposta gerada localmente. Conecte a chave Gemini para classificação semântica.', tags: [], actions: [], confidence: 35, markdown: '' }; }
function buildMarkdown(item: Proposal, sourcePath: string) { const metadata = [`id: ${item.id}`, `title: ${item.title}`, `original_file: ${item.relativePath}`, `source_path: ${sourcePath || 'não informado'}`, `type: ${item.type}`, `modified: ${item.modified}`, `para: ${item.para}`, `parent: ${item.parent || 'sem vínculo'}`, `tags: [${item.tags.map(tag => JSON.stringify(tag)).join(', ')}]`].join('\n'); const body = [`# ${item.title}`, '', item.summary, item.actions.length ? `## Próximas ações\n${item.actions.map(action => `- [ ] ${action}`).join('\n')}` : ''].filter(Boolean).join('\n\n'); return `---\n${metadata}\n---\n\n${limit(body)}`; }

export default function DadosIngestao() {
  const inputRef = useRef<HTMLInputElement>(null); const { addBatchItems } = useStore();
  const [items, setItems] = useState<SourceItem[]>([]); const [proposals, setProposals] = useState<Proposal[]>([]); const [sourcePath, setSourcePath] = useState(''); const [ignoredCount, setIgnoredCount] = useState(0); const [folderNames, setFolderNames] = useState<Record<string, string>>({}); const [editingFolder, setEditingFolder] = useState<string | null>(null);
  const [state, setState] = useState<'idle' | 'reading' | 'analyzing' | 'ready' | 'saved' | 'error'>('idle'); const [message, setMessage] = useState('Selecione arquivos ou um ZIP. Nada é movido nem enviado antes da análise.');
  const selected = items.filter(item => item.selected); const folders = useMemo(() => items.reduce<Record<string, SourceItem[]>>((groups, item) => { const folder = item.relativePath.split('/').slice(0, -1).join('/') || 'Arquivos na raiz'; (groups[folder] ||= []).push(item); return groups; }, {}), [items]);
  const readFile = async (file: File): Promise<{ items: SourceItem[]; ignored: number }> => { if (extension(file.name) !== 'zip') { const canRead = textExtensions.has(extension(file.name)); return { items: [baseItem(file.name, file.size, canRead ? limit(await file.text(), 8000) : '', new Date(file.lastModified).toISOString().slice(0, 10))], ignored: 0 }; } const zip = await JSZip.loadAsync(file); const entries = Object.values(zip.files).filter(entry => !entry.dir); const useful = entries.filter(entry => !isNoise(entry.name)).slice(0, 80); const next = await Promise.all(useful.map(async entry => baseItem(entry.name, 0, textExtensions.has(extension(entry.name)) ? limit(await entry.async('text'), 8000) : '', new Date().toISOString().slice(0, 10)))); return { items: next, ignored: entries.length - useful.length }; };
  const onFiles = async (event: React.ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files || []); if (!files.length) return; setState('reading'); setMessage('Lendo a estrutura dos arquivos…'); try { const batches = await Promise.all(files.slice(0, 20).map(readFile)); const next = batches.flatMap(batch => batch.items); const ignored = batches.reduce((total, batch) => total + batch.ignored, 0); setItems(next); setIgnoredCount(ignored); setFolderNames({}); setEditingFolder(null); setProposals([]); setState('idle'); setMessage(`${next.length} arquivo(s) útil(eis) encontrado(s). Escolha o que vai para o Gemini.`); } catch { setState('error'); setMessage('Não foi possível abrir um dos arquivos. Tente um ZIP ou arquivos menores.'); } };
  const toggleItem = (id: string) => setItems(current => current.map(item => item.id === id ? { ...item, selected: !item.selected } : item));
  const setSelection = (mode: 'all' | 'recommended' | 'document' | 'code' | 'none') => setItems(current => current.map(item => ({ ...item, selected: mode === 'all' ? true : mode === 'recommended' ? item.kind === 'document' || item.kind === 'code' : item.kind === mode })));
  const analyze = async () => { if (!selected.length) { setState('error'); setMessage('Marque ao menos um arquivo para analisar.'); return; } if (selected.length > 20) { setState('error'); setMessage('Para uma análise confiável, selecione até 20 arquivos por vez.'); return; } const credential = getGeminiCredential(); if (!credential.apiKey) { setState('error'); setMessage('Salve e teste a chave Gemini em Dados → Credenciais antes de analisar.'); return; } setState('analyzing'); setMessage(`Analisando ${selected.length} arquivo(s) selecionado(s)…`); const compact = selected.map(item => ({ id: item.id, name: item.relativePath, type: item.type, excerpt: limit(item.excerpt, 700) })); const prompt = `Você organiza um segundo cérebro pelo método PARA. Classifique cada item em project, area, resource ou archive. Retorne SOMENTE JSON válido: {"items":[{"id":"","para":"project|area|resource|archive","title":"","parent":"","summary":"até 300 caracteres","tags":[""],"actions":[""],"confidence":0}]}. Não invente fatos. Itens: ${JSON.stringify(compact)}`; try { const ai = new GoogleGenAI({ apiKey: credential.apiKey }); const result = await ai.models.generateContent({ model: credential.model, contents: prompt, config: { temperature: 0.2, maxOutputTokens: 3000 } }); const parsed = JSON.parse(cleanJson(result.text || '{}')) as { items?: Array<Partial<Proposal>> }; const byId = new Map((parsed.items || []).map(item => [item.id, item])); const next = selected.map(item => { const aiItem = byId.get(item.id); const base = aiItem?.para && ['project', 'area', 'resource', 'archive'].includes(aiItem.para) ? { ...fallback(item), ...aiItem, para: aiItem.para as Para } : fallback(item); return { ...base, tags: Array.isArray(base.tags) ? base.tags.slice(0, 8) : [], actions: Array.isArray(base.actions) ? base.actions.slice(0, 5) : [], confidence: Number(base.confidence) || 0, markdown: '' } as Proposal; }).map(item => ({ ...item, markdown: buildMarkdown(item, sourcePath) })); setProposals(next); setState('ready'); setMessage('Proposta pronta. Revise antes de integrar ao Knowledge Intake.'); } catch (error) { const detail = error instanceof Error ? error.message : String(error); setState('error'); setMessage(detail.includes('429') ? 'A cota Gemini foi atingida. Tente novamente depois.' : `A análise falhou: ${detail.slice(0, 140)}`); } };
  const updateProposal = (id: string, patch: Partial<Proposal>) => setProposals(current => current.map(item => { const next = { ...item, ...patch } as Proposal; return { ...next, markdown: buildMarkdown(next, sourcePath) }; }));
  const integrate = () => { const saved = JSON.parse(localStorage.getItem(intakeKey) || '[]'); localStorage.setItem(intakeKey, JSON.stringify([...saved, ...proposals.map(({ markdown, ...item }) => ({ ...item, markdown, createdAt: new Date().toISOString() }))])); addBatchItems?.({ areas: proposals.filter(item => item.para === 'area').map(item => ({ name: item.title, icon: '◌' })), projects: proposals.filter(item => item.para === 'project').map(item => ({ title: item.title, desc: item.summary, area: item.parent || 'Inbox', status: 'active' as const })), resources: proposals.filter(item => item.para === 'resource' || item.para === 'archive').map(item => ({ title: item.title, area: item.parent || (item.para === 'archive' ? 'Arquivados' : 'Inbox') })), tasks: proposals.flatMap(item => item.actions.map(title => ({ title, area: item.parent || 'Inbox', project: item.para === 'project' ? item.title : undefined, priority: 'P 2', battleTokens: '0', status: 'not-started' as const }))) }); setState('saved'); setMessage('Aprovado: registros e MDs foram adicionados ao Knowledge Intake deste navegador.'); };
  const download = async () => { const zip = new JSZip(); proposals.forEach(item => zip.file(`${item.title.replace(/[^a-z0-9-_ ]/gi, '').slice(0, 80) || item.id}.md`, item.markdown)); const blob = await zip.generateAsync({ type: 'blob' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'para-organizer-md.zip'; link.click(); URL.revokeObjectURL(url); };
  const ItemIcon = ({ item }: { item: SourceItem }) => item.kind === 'image' ? <FileImage className="h-4 w-4 text-forest" /> : item.kind === 'code' ? <FileCode2 className="h-4 w-4 text-forest" /> : <FileText className="h-4 w-4 text-forest" />;
  return <div className="mx-auto flex w-full max-w-6xl flex-col gap-5 pb-10">
    <div className="rounded-2xl border border-forest/10 bg-white p-6 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-forest" /><h2 className="text-[18px] font-bold text-ink">Ingestão PARA</h2></div><p className="mt-1 text-[13px] text-ink/60">Arquivo ou ZIP → seleção → Gemini → proposta revisável → Markdown + Knowledge Intake.</p></div><span className="flex items-center gap-2 rounded-xl bg-forest/5 px-3 py-2 text-[11px] font-bold text-forest"><ShieldCheck className="h-4 w-4" /> Aprovação obrigatória</span></div><div className="mt-5 grid gap-4 md:grid-cols-[1fr_280px]"><button onClick={() => inputRef.current?.click()} className="flex min-h-36 flex-col items-center justify-center rounded-2xl border-2 border-dashed border-forest/20 bg-forest/3 p-5 text-center transition hover:border-forest/45 hover:bg-forest/5"><FolderUp className="h-8 w-8 text-forest" /><span className="mt-2 text-[14px] font-bold text-ink">Selecionar arquivos ou ZIP</span><span className="mt-1 text-[11px] text-ink/50">A estrutura é preservada; lixo técnico é ignorado.</span></button><div className="rounded-2xl border border-forest/10 p-4"><label className="text-[12px] font-bold text-ink/70">Caminho original (opcional)</label><input value={sourcePath} onChange={event => setSourcePath(event.target.value)} placeholder="/Users/Pedro/..." className="mt-2 h-10 w-full rounded-xl border border-forest/15 px-3 text-[12px] outline-none focus:border-forest/40" /><p className="mt-2 text-[11px] text-ink/45">O navegador não consegue descobrir esse caminho sozinho.</p></div></div><input ref={inputRef} onChange={onFiles} type="file" multiple className="hidden" accept=".zip,.md,.txt,.csv,.json,.sql,.py,.ipynb,.pdf,.doc,.docx,.xlsx,.png,.jpg" /><div className="mt-4 flex flex-wrap items-center gap-3"><button onClick={analyze} disabled={!selected.length || state === 'reading' || state === 'analyzing'} className="flex items-center gap-2 rounded-xl bg-forest px-4 py-2.5 text-[12px] font-bold text-white disabled:opacity-40">{state === 'analyzing' || state === 'reading' ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4 fill-white" />} Analisar {selected.length ? `(${selected.length})` : ''} com Gemini</button><p className={`text-[12px] font-medium ${state === 'error' ? 'text-red-700' : 'text-ink/55'}`}>{message}</p></div></div>
    {!!items.length && <div className="rounded-2xl border border-forest/10 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-[14px] font-bold text-ink">Estrutura encontrada</h3><p className="mt-1 text-[11px] text-ink/50">{selected.length} selecionado(s){ignoredCount ? ` · ${ignoredCount} item(ns) técnico(s) ignorado(s)` : ''}</p></div><div className="flex flex-wrap items-center gap-2"><button onClick={() => setSelection('recommended')} className="rounded-lg border border-forest/15 px-3 py-2 text-[11px] font-bold text-forest">Recomendados</button><button onClick={() => setSelection('document')} className="rounded-lg border border-forest/15 px-3 py-2 text-[11px] font-bold text-forest">Documentos</button><button onClick={() => setSelection('code')} className="rounded-lg border border-forest/15 px-3 py-2 text-[11px] font-bold text-forest">Códigos</button><button onClick={() => setSelection('all')} className="rounded-lg border border-forest/15 px-3 py-2 text-[11px] font-bold text-forest">Todos</button><button aria-label="Limpar seleção" onClick={() => setSelection('none')} className="px-1 text-[11px] font-bold text-ink/45 hover:text-forest">Limpar</button></div></div><div className="mt-4 space-y-4">{(Object.entries(folders) as [string, SourceItem[]][]).sort(([a], [b]) => a.localeCompare(b)).map(([folder, group]) => <div key={folder}><div className="mb-2 flex items-center gap-2 text-[11px] font-bold text-forest"><Folder className="h-4 w-4" />{editingFolder === folder ? <input autoFocus value={folderNames[folder] ?? folder} onChange={event => setFolderNames(current => ({ ...current, [folder]: event.target.value }))} onBlur={() => setEditingFolder(null)} onKeyDown={event => { if (event.key === 'Enter') setEditingFolder(null); }} className="h-6 w-72 rounded border border-forest/20 px-2 text-[11px] outline-none" /> : <><span>{folderNames[folder] || folder}</span><button aria-label={`Editar nome exibido de ${folder}`} onClick={() => setEditingFolder(folder)} className="rounded p-1 text-forest/55 hover:bg-forest/8 hover:text-forest"><Pencil className="h-3.5 w-3.5" /></button></>}</div><div className="grid gap-2 md:grid-cols-2">{group.map(item => <label key={item.id} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 transition ${item.selected ? 'border-forest/20 bg-forest/5' : 'border-forest/8 bg-white opacity-70'}`}><ItemIcon item={item} /><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-bold text-ink">{item.name}</p><p className="text-[10px] text-ink/50">{item.type} · {humanSize(item.size)}</p></div><input aria-label={`Selecionar ${item.name}`} type="checkbox" checked={item.selected} onChange={() => toggleItem(item.id)} className="h-4 w-4 accent-forest" /></label>)}</div></div>)}</div></div>}
    {!!proposals.length && <div className="rounded-2xl border border-forest/10 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-[14px] font-bold text-ink">Revisão antes de aprovar</h3><p className="text-[11px] text-ink/50">Cada MD tem no máximo 2.200 caracteres; metadados ficam fora desse limite.</p></div><div className="flex gap-2"><button onClick={download} className="flex items-center gap-2 rounded-xl border border-forest/15 px-3 py-2 text-[12px] font-bold text-forest"><Download className="h-4 w-4" /> Baixar MDs</button><button onClick={integrate} className="flex items-center gap-2 rounded-xl bg-forest px-3 py-2 text-[12px] font-bold text-white"><CheckCircle2 className="h-4 w-4" /> Aprovar e integrar</button></div></div><div className="mt-4 space-y-3">{proposals.map(item => <div key={item.id} className="rounded-xl border border-forest/10 p-4"><div className="grid gap-3 md:grid-cols-[1.2fr_.65fr_.8fr]"><div><label className="text-[10px] font-bold uppercase text-ink/45">Título</label><input value={item.title} onChange={event => updateProposal(item.id, { title: event.target.value })} className="mt-1 h-9 w-full rounded-lg border border-forest/15 px-2 text-[12px]" /></div><div><label className="text-[10px] font-bold uppercase text-ink/45">PARA</label><select value={item.para} onChange={event => updateProposal(item.id, { para: event.target.value as Para })} className="mt-1 h-9 w-full rounded-lg border border-forest/15 px-2 text-[12px]">{Object.entries(paraLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div><label className="text-[10px] font-bold uppercase text-ink/45">Pai</label><input value={item.parent} onChange={event => updateProposal(item.id, { parent: event.target.value })} className="mt-1 h-9 w-full rounded-lg border border-forest/15 px-2 text-[12px]" /></div></div><p className="mt-3 text-[12px] leading-relaxed text-ink/70">{item.summary}</p><div className="mt-2 flex items-center gap-2 text-[10px] text-ink/45"><FileText className="h-3.5 w-3.5" /> {item.relativePath} · confiança {item.confidence}%</div></div>)}</div></div>}
    {state === 'saved' && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-[13px] font-bold text-emerald-800"><Check className="mr-2 inline h-4 w-4" />Integração concluída neste navegador.</div>}
  </div>;
}
