import { View } from '../../store';

export type ScreenRenderKind = 'live' | 'captured';

export interface ScreenMetadata {
  id: string;
  title: string;
  journey: string;
  section: string;
  route: View;
  subtab?: string;
  componentName: string;
  description: string;
  states: string[];
  dataUsed: string;
  x: number;
  y: number;
  renderKind: ScreenRenderKind;
  viewportDesktop: boolean;
  viewportMobile: boolean;
  coverageStatus: 'covered' | 'pending';
  captureMetadata?: {
    capturedAt: string;
    viewport: string;
  };
}

export const SCREEN_REGISTRY: ScreenMetadata[] = [
  // Jornada 1: Entrada & Visão Geral
  {
    id: 'S01-home',
    title: 'Visão Geral (Home)',
    journey: 'Entrada & Visão Geral',
    section: 'Início',
    route: 'home',
    componentName: 'HomeView',
    description: 'Resumo panorâmico do dia, tokens de batalha, radar de execução e hábitos.',
    states: ['Padrão', 'Vazio', 'Carregando'],
    dataUsed: 'tasks (hoje), habits, projects ativos, metrics',
    x: 0,
    y: 0,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S02-quick-capture',
    title: 'Captura Rápida',
    journey: 'Entrada & Visão Geral',
    section: 'Início',
    route: 'quick-capture',
    componentName: 'QuickCaptureView',
    description: 'Despejo mental rápido de notas e tarefas sem categorização prévia.',
    states: ['Padrão', 'Validação (vazio)', 'Sucesso'],
    dataUsed: 'tasks (área Inbox)',
    x: 520,
    y: 0,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },

  // Jornada 2: Agenda & Execução
  {
    id: 'S03-take-action',
    title: 'Take Action',
    journey: 'Agenda & Execução',
    section: 'Agenda',
    route: 'take-action',
    componentName: 'TakeActionView',
    description: 'Foco na execução das tarefas prioritárias ordenadas por urgência e naipes.',
    states: ['Padrão', 'Vazio (radar limpo)', 'Filtro ativo'],
    dataUsed: 'tasks com status not-started / in-progress',
    x: 0,
    y: 420,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S04-weeks',
    title: 'Weeks (Planejador)',
    journey: 'Agenda & Execução',
    section: 'Agenda',
    route: 'weeks',
    componentName: 'WeeksView',
    description: 'Planejamento semanal em colunas diárias com alocação e prazos.',
    states: ['Padrão', 'Vazio por dia', 'Drag & Drop'],
    dataUsed: 'tasks com executionDate e day',
    x: 520,
    y: 420,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S05-journal',
    title: 'Journal (Diário)',
    journey: 'Agenda & Execução',
    section: 'Agenda',
    route: 'journal',
    componentName: 'JournalView',
    description: 'Registro de reflexões e notas diárias com histórico em linha do tempo.',
    states: ['Padrão', 'Vazio', 'Edição ativa'],
    dataUsed: 'entradas de diário no store',
    x: 1040,
    y: 420,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },

  // Jornada 3: Gestão PARA
  {
    id: 'S06-projects',
    title: 'Projetos (Grid/Lista)',
    journey: 'Gestão PARA',
    section: 'PARA',
    route: 'projects',
    componentName: 'ProjectsView',
    description: 'Quadro executivo de projetos com cálculo de progresso e filtros de área.',
    states: ['Padrão (Grid)', 'Visualização em Lista', 'Vazio'],
    dataUsed: 'projects, tasks vinculadas, areas',
    x: 0,
    y: 840,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S07-project-detail',
    title: 'Detalhe do Projeto',
    journey: 'Gestão PARA',
    section: 'PARA',
    route: 'projects',
    componentName: 'ProjectDetailView',
    description: 'Gestão granular de tarefas e marcos de um projeto específico.',
    states: ['Padrão', 'Vazio (sem tarefas)', 'Tarefa Concluída'],
    dataUsed: 'project selecionado, tasks do projeto',
    x: 520,
    y: 840,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S08-tasks',
    title: 'Tarefas (Tasks)',
    journey: 'Gestão PARA',
    section: 'PARA',
    route: 'tasks',
    componentName: 'TasksView',
    description: 'Tabela de alta densidade estilo Goldman Sachs com filtros de status.',
    states: ['Padrão', 'Vazio', 'Filtro sem resultados'],
    dataUsed: 'tasks, areas, projects',
    x: 1040,
    y: 840,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S09-areas',
    title: 'Áreas da Vida',
    journey: 'Gestão PARA',
    section: 'PARA',
    route: 'areas',
    componentName: 'AreasView',
    description: 'Esferas contínuas de responsabilidade e manutenção pessoal.',
    states: ['Padrão', 'Vazio', 'Modal de Nova Área'],
    dataUsed: 'areas, contagem de projetos',
    x: 0,
    y: 1260,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S10-area-detail',
    title: 'Detalhe da Área',
    journey: 'Gestão PARA',
    section: 'PARA',
    route: 'areas',
    componentName: 'AreaDetailView',
    description: 'Visão agregada de projetos e recursos vinculados a uma área.',
    states: ['Padrão', 'Vazio por aba'],
    dataUsed: 'area selecionada, projects, resources',
    x: 520,
    y: 1260,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S11-recursos',
    title: 'Recursos',
    journey: 'Gestão PARA',
    section: 'PARA',
    route: 'recursos',
    componentName: 'RecursosView',
    description: 'Repositório permanente de materiais de referência, apostilas e links.',
    states: ['Padrão', 'Vazio', 'Busca sem resultados'],
    dataUsed: 'resources, areas, projects',
    x: 1040,
    y: 1260,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S12-arquivados',
    title: 'Arquivados',
    journey: 'Gestão PARA',
    section: 'PARA',
    route: 'arquivados',
    componentName: 'ArquivadosView',
    description: 'Histórico de projetos e tarefas concluídas com restauração.',
    states: ['Padrão', 'Vazio', 'Confirmação de Exclusão'],
    dataUsed: 'tasks e projetos arquivados',
    x: 1560,
    y: 1260,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },

  // Jornada 4: Sistema & Rotina
  {
    id: 'S13-inbox',
    title: 'Inbox (Pendentes)',
    journey: 'Sistema & Rotina',
    section: 'Sistema',
    route: 'inbox',
    componentName: 'InboxView',
    description: 'Caixa de triagem para classificar ou arquivar itens não processados.',
    states: ['Padrão', 'Inbox Zero (Vazio)'],
    dataUsed: 'tasks na área Inbox',
    x: 0,
    y: 1680,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S14-habitos',
    title: 'Hábitos & Rotinas',
    journey: 'Sistema & Rotina',
    section: 'Sistema',
    route: 'habitos',
    componentName: 'HabitosView',
    description: 'Rastreamento semanal de hábitos com matriz de dias e sequências ativas.',
    states: ['Padrão', 'Vazio', 'Streak Alto'],
    dataUsed: 'habits, matriz semanal',
    x: 520,
    y: 1680,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },

  // Jornada 5: Dados & Córtex
  {
    id: 'S15-dados-cortex',
    title: 'Dados / Córtex (KI)',
    journey: 'Dados & Córtex',
    section: 'Dados',
    route: 'dados',
    subtab: 'cortex',
    componentName: 'DadosCortex',
    description: 'Tabela unificada de nós da Single Source of Truth no IndexedDB.',
    states: ['Padrão', 'Vazio', 'Carregando do DB'],
    dataUsed: 'nodes, relations do IndexedDB',
    x: 0,
    y: 2100,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S16-dados-credentials',
    title: 'Dados / Credenciais',
    journey: 'Dados & Córtex',
    section: 'Dados',
    route: 'dados',
    subtab: 'credentials',
    componentName: 'CredentialsView',
    description: 'Configuração da chave Gemini API, seleção de modelo e teste local.',
    states: ['Chave Configurada', 'Sem Credencial', 'Erro de Chave'],
    dataUsed: 'credenciais locais (localStorage)',
    x: 520,
    y: 2100,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S17-dados-registros',
    title: 'Dados / Log Diário',
    journey: 'Dados & Córtex',
    section: 'Dados',
    route: 'dados',
    subtab: 'registros',
    componentName: 'DadosRegistros',
    description: 'Histórico inquebrável de eventos e registros do sistema.',
    states: ['Padrão', 'Vazio'],
    dataUsed: 'registros do store',
    x: 1040,
    y: 2100,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S18-dados-explorador',
    title: 'Dados / Explorador Raw',
    journey: 'Dados & Córtex',
    section: 'Dados',
    route: 'dados',
    subtab: 'explorador',
    componentName: 'DadosExplorador',
    description: 'Acesso granular e tabular a todas as ramificações de dados.',
    states: ['Padrão', 'Filtro por Tabela'],
    dataUsed: 'todas as coleções',
    x: 1560,
    y: 2100,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S19-dados-analytics',
    title: 'Dados / BI & Analytics',
    journey: 'Dados & Córtex',
    section: 'Dados',
    route: 'dados',
    subtab: 'analytics',
    componentName: 'DadosAnalytics',
    description: 'Gráficos analíticos e KPIs em estilo Power BI.',
    states: ['Padrão', 'Vazio'],
    dataUsed: 'métricas agregadas',
    x: 2080,
    y: 2100,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S20-dados-relacional',
    title: 'Dados / Relacional Raw',
    journey: 'Dados & Córtex',
    section: 'Dados',
    route: 'dados',
    subtab: 'relacional',
    componentName: 'DadosRelacional',
    description: 'Inspeção de relações entre entidades no modelo relacional bruto.',
    states: ['Padrão', 'Vazio'],
    dataUsed: 'tabelas do store',
    x: 2600,
    y: 2100,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },

  // Jornada 6: Para-Organizer
  {
    id: 'S21-para-overview',
    title: 'Para-Organizer / Visão Geral',
    journey: 'Para-Organizer',
    section: 'Para-Organizer',
    route: 'para-organizer',
    subtab: 'overview',
    componentName: 'ParaOrganizerSkillView',
    description: 'Apresentação da skill, métricas de capacidade e instruções.',
    states: ['Skill Ativa', 'Skill Inativa'],
    dataUsed: 'metadados da skill',
    x: 0,
    y: 2520,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S22-para-content',
    title: 'Para-Organizer / Conteúdo',
    journey: 'Para-Organizer',
    section: 'Para-Organizer',
    route: 'para-organizer',
    subtab: 'content',
    componentName: 'ParaOrganizerSkillView',
    description: 'Visualizador dos arquivos markdown da skill com botão de cópia.',
    states: ['Visualização', 'Código', 'Copiado'],
    dataUsed: 'textos de documentação',
    x: 520,
    y: 2520,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S23-para-upload',
    title: 'Para-Organizer / Ingestão & Pipeline',
    journey: 'Para-Organizer',
    section: 'Para-Organizer',
    route: 'para-organizer',
    subtab: 'upload',
    componentName: 'DadosIngestao',
    description: 'Pipeline completo de upload/ZIP, SHA-256, Gemini e aprovação.',
    states: ['Vazio', 'Extraindo', 'Propostas Prontas', 'Aprovado', 'Erro >100MB'],
    dataUsed: 'arquivos locais, ZIP, Web Crypto, Gemini',
    x: 1040,
    y: 2520,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },

  // Jornada 7: Memória Relacional
  {
    id: 'S24-memoria-mapa',
    title: 'Memória / Mapa Relacional (D3)',
    journey: 'Memória Relacional',
    section: 'Memória',
    route: 'memoria',
    subtab: 'mapa',
    componentName: 'MemoriaMapa',
    description: 'Grafo radial/esférico estilo Obsidian com force layout D3.',
    states: ['Padrão', 'Zoom/Pan', 'Nó Selecionado', 'Vazio'],
    dataUsed: 'nodes, relations do KI',
    x: 0,
    y: 2940,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S25-memoria-nos',
    title: 'Memória / Nós',
    journey: 'Memória Relacional',
    section: 'Memória',
    route: 'memoria',
    subtab: 'nos',
    componentName: 'MemoriaNos',
    description: 'Lista pesquisável e tabular de todos os nós de conhecimento.',
    states: ['Padrão', 'Busca ativa', 'Vazio'],
    dataUsed: 'nodes do KI',
    x: 520,
    y: 2940,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S26-memoria-relacoes',
    title: 'Memória / Relações',
    journey: 'Memória Relacional',
    section: 'Memória',
    route: 'memoria',
    subtab: 'relacoes',
    componentName: 'MemoriaRelacoes',
    description: 'Criação, revisão e aprovação de arestas conectando nós.',
    states: ['Padrão', 'Sugestão IA Pendente', 'Vazio'],
    dataUsed: 'relations do KI',
    x: 1040,
    y: 2940,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
  {
    id: 'S27-memoria-orfaos',
    title: 'Memória / Órfãos',
    journey: 'Memória Relacional',
    section: 'Memória',
    route: 'memoria',
    subtab: 'orfaos',
    componentName: 'MemoriaOrfaos',
    description: 'Itens desconectados para saneamento e manutenção do cérebro.',
    states: ['Padrão com Órfãos', 'Sem Órfãos (Limpo)'],
    dataUsed: 'nós com grau de conexão zero',
    x: 1560,
    y: 2940,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },

  // Jornada 8: Assistência IA
  {
    id: 'S28-jarvis',
    title: 'Assistente Jarvis',
    journey: 'Assistência IA',
    section: 'Jarvis',
    route: 'home',
    componentName: 'JarvisChat',
    description: 'Chat consultivo com modelo Gemini e cartões de proposta com aprovação humana.',
    states: ['Minimizado', 'Aberto', 'Digitando', 'Proposta Pendente', 'Sem Credencial'],
    dataUsed: 'chat history, Gemini API, store context',
    x: 0,
    y: 3360,
    renderKind: 'live',
    viewportDesktop: true,
    viewportMobile: true,
    coverageStatus: 'covered',
  },
];

// Funções Canônicas de Cálculo (Sem Valores Hardcoded)
export const getScreenCount = (): number => SCREEN_REGISTRY.length;
export const getDesktopFrameCount = (): number => SCREEN_REGISTRY.filter(s => s.viewportDesktop).length;
export const getMobileFrameCount = (): number => SCREEN_REGISTRY.filter(s => s.viewportMobile).length;
export const getTotalFrameCount = (): number => getDesktopFrameCount() + getMobileFrameCount();
export const getJourneys = (): string[] => Array.from(new Set(SCREEN_REGISTRY.map(s => s.journey)));
export const getScreenById = (id: string): ScreenMetadata | undefined => SCREEN_REGISTRY.find(s => s.id === id);
